language: node_js

env:
  - CXX=g++-4.8

node_js:
  - 7

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8

sudo: false

before_install:
  - $CXX --version

after_script:
  - npm run coveralls
